### ISSUE TITLE
Filename not recognized

### ISSUE THREAD

**Issue by mirisbowring** [docspell/android-client#31]
Hi,

first of all:
**Thank you for the nice tool!**

I am coming from paperless and am evaluating docspell as the future alternative.

**Here is my Problem:**
I've setup all components and everything runs smoothly.
But when i upload a document (e.x. pdf) from my Android Phone, the name is not kept.

e.x. "2021-05-18 hotel recipe.pdf" is beeing converted to sth like `137887.pdf` Also in the Uploading dialog of the App this number is displayed.

Later in the WebUI, the converted pdf, the original and the document name are this number (every new document gets a new unique number).

Is this expected or a bug?

Regards!

**Comment by eikek** [comment]
Hi @mirisbowring thank you!

I'd say this is a bug - but I'm not yet sure how to solve this. The app uses the file name by extracting it from the url that is given by the app that shared the file. I need to do some research on how to improve this. (tips welcome ;-))

What app do you use for sharing the file? For example, I'm using OpenNoteScanner most of the time, where the filenames are correctly transported to docspell.

**Comment by monnypython** [comment]
For me it is at the moment that the file name is taken over correctly, but a "primary: ....." is set in front of each name.
![image](https://user-images.githubusercontent.com/42573701/124978047-8f78a580-e031-11eb-94a2-884fc79f4ca4.png)

**Comment by eikek** [comment]
That's interesting! What apps are you using to share files? I could then try to find them and do some testing. I guess I have to read up on some android resources again :).

**Comment by monnypython** [comment]
The different apps behave differently. I only use apps from the f-froid store. I tested the following:
- shared with "Zeichenblock", "Nextcloud files app": file name as expected
- shared with "PDF Viewer plus": file name is replaced by a 3-digit number
- File manager lineage os: "primary:" is put in front

**Comment by eikek** [comment]
Thank you! I just tried with PDF Viewer plus from fdroid. On my phone, the docspell app adds a prefix; seems like the device name. This is good to play with now.

**Comment by monnypython** [comment]
Another example: When uploading an image from my gallery app, a 6-digit number is generated. e.g .: 104853.jpg

[SimpleMobileTools / Simple-Gallery] (https://github.com/SimpleMobileTools/Simple-Gallery)

**Comment by mirisbowring** [comment]
For me, this happens when sharing from Huawei "Files" App and "Drive PDF Viewer". 
-> Both are converting the name into a digit number.

When sharing from "Genius Scan" App, this does not happen - Great! :D

**Comment by mirisbowring** [comment]
Just for your information. The Paperless-Share app is aware of the filenames (at least for the apps, i am using).
Probably you find a solution in their repo for the problem? 😊 
https://github.com/qcasey/paperless_share

**Comment by mirisbowring** [comment]
![image](https://user-images.githubusercontent.com/15715080/156003546-98821fd9-1286-4f0d-b65b-7264cab6b33c.png)

I see, that docspellshare is using the document id as name instead of the actual name (see screenshot)
