### ISSUE TITLE
sharing multiple documents does not work

### ISSUE THREAD

**Issue by monnypython** [docspell/android-client#32]
First of all, thank you very much for the great app! I use them very much and regularly;).

But I noticed one problem:
If several files have been selected on the smartphone and are to be shared with "Docspell Share", apparently all files are sent, but Docspell only ever receives one document.

**Comment by eikek** [comment]
Oh what a bug! Thanks for reporting. I never tried to share more than one :-)

**Comment by eikek** [comment]
I just tested it with Docspell 0.25.1 and it works there. So the problem was at the server. So I'm closing this, should I be wrong, just reopen of course.

**Comment by monnypython** [comment]
Works for me too.
