### ISSUE TITLE
Cleartext http traffic not allowed in version 0.5.0

### ISSUE THREAD

**Issue by eikek** [docspell/android-client#7]
See https://app.element.io/#/room/#eikek_docspell:gitter.im/$efZjWvfIHRddug3LbOSRUhwmL7W-DVcsNMwqXQ-2v9w

The current version ( 0.5.0) enforces https. I'd like to allow http traffic for this app, because I think that the use case of having docspell only in the internal LAN in ones home warrants using http instead of setting up ssl certificates…. It would be nice, if this could be explicitly enabled by the user, but my little android know-how must be expanded for this…:) 

Workaround: use version 0.4.0 for now if you need cleartext traffic.

**Comment by gerroon** [comment]
Hi 

This would be great, I am using it over VPN and I do not need https. I think that is why this app is failing to upload anything.

**Comment by eikek** [comment]
Yes this was not possible. I think I found the setting required for this in #61. You can try the nightly release to test it.

**Comment by eikek** [comment]
I release 0.8.0 with this change, it usually is on fdroid in about a few days.
